<?xml version="1.0" encoding="utf-8"?><Profile xmlns="http://soap.sforce.com/2006/04/metadata"><custom>true</custom><description>Used for Quality Assurance testers. Assigned in the sandboxes.</description><userLicense>Salesforce</userLicense><classAccesses>
        <apexClass>CampaignMemberManagementController</apexClass>
        <enabled>true</enabled>
    </classAccesses><classAccesses>
        <apexClass>DataComHierarchiesControllerExtension</apexClass>
        <enabled>true</enabled>
    </classAccesses><classAccesses>
        <apexClass>NewCorporateRelationsContactController</apexClass>
        <enabled>true</enabled>
    </classAccesses><classAccesses>
        <apexClass>TopFiveArticleController</apexClass>
        <enabled>true</enabled>
    </classAccesses><classAccesses>
        <apexClass>UnifiedProspectPageController</apexClass>
        <enabled>true</enabled>
    </classAccesses><pageAccesses>
        <apexPage>CampaignMemberManagement</apexPage>
        <enabled>true</enabled>
    </pageAccesses><pageAccesses>
        <apexPage>CaseShowAllAttachments</apexPage>
        <enabled>true</enabled>
    </pageAccesses><pageAccesses>
        <apexPage>CaseTransfer</apexPage>
        <enabled>true</enabled>
    </pageAccesses><pageAccesses>
        <apexPage>CommunicationHistory</apexPage>
        <enabled>true</enabled>
    </pageAccesses><pageAccesses>
        <apexPage>DataComHierarchies</apexPage>
        <enabled>true</enabled>
    </pageAccesses><pageAccesses>
        <apexPage>DynamicFeedback</apexPage>
        <enabled>true</enabled>
    </pageAccesses><pageAccesses>
        <apexPage>LeadCommunicationHistory</apexPage>
        <enabled>true</enabled>
    </pageAccesses><pageAccesses>
        <apexPage>NewCorporateRelationsContact</apexPage>
        <enabled>true</enabled>
    </pageAccesses><pageAccesses>
        <apexPage>PeopleSoft_Financial_Aid_Case_Button</apexPage>
        <enabled>true</enabled>
    </pageAccesses><pageAccesses>
        <apexPage>ProfileAudit</apexPage>
        <enabled>true</enabled>
    </pageAccesses><pageAccesses>
        <apexPage>Unified_Prospect_Page</apexPage>
        <enabled>true</enabled>
    </pageAccesses><pageAccesses>
        <apexPage>feedback</apexPage>
        <enabled>true</enabled>
    </pageAccesses><pageAccesses>
        <apexPage>loading</apexPage>
        <enabled>true</enabled>
    </pageAccesses><pageAccesses>
        <apexPage>systemoutage</apexPage>
        <enabled>true</enabled>
    </pageAccesses><applicationVisibilities>
        <application>ASU_Chatter</application>
        <default>false</default>
        <visible>false</visible>
    </applicationVisibilities><applicationVisibilities>
        <application>ASU_Corporate_Relations</application>
        <default>false</default>
        <visible>true</visible>
    </applicationVisibilities><applicationVisibilities>
        <application>ASU_Organizational_Relationships</application>
        <default>false</default>
        <visible>true</visible>
    </applicationVisibilities><applicationVisibilities>
        <application>ASU_QA</application>
        <default>true</default>
        <visible>true</visible>
    </applicationVisibilities><applicationVisibilities>
        <application>ASU_Read_Only</application>
        <default>false</default>
        <visible>true</visible>
    </applicationVisibilities><applicationVisibilities>
        <application>ASU_Service</application>
        <default>false</default>
        <visible>true</visible>
    </applicationVisibilities><applicationVisibilities>
        <application>Administrator</application>
        <default>false</default>
        <visible>false</visible>
    </applicationVisibilities><applicationVisibilities>
        <application>Knowledge</application>
        <default>false</default>
        <visible>false</visible>
    </applicationVisibilities><applicationVisibilities>
        <application>PKB_2</application>
        <default>false</default>
        <visible>false</visible>
    </applicationVisibilities><applicationVisibilities>
        <application>Success_Engagement_Management</application>
        <default>false</default>
        <visible>false</visible>
    </applicationVisibilities><applicationVisibilities>
        <application>Success_Portal_Management</application>
        <default>false</default>
        <visible>false</visible>
    </applicationVisibilities><applicationVisibilities>
        <application>standard__AppLauncher</application>
        <default>false</default>
        <visible>false</visible>
    </applicationVisibilities><applicationVisibilities>
        <application>standard__Chatter</application>
        <default>false</default>
        <visible>false</visible>
    </applicationVisibilities><applicationVisibilities>
        <application>standard__Community</application>
        <default>false</default>
        <visible>false</visible>
    </applicationVisibilities><applicationVisibilities>
        <application>standard__DataAssessment</application>
        <default>false</default>
        <visible>true</visible>
    </applicationVisibilities><applicationVisibilities>
        <application>standard__Insights</application>
        <default>false</default>
        <visible>true</visible>
    </applicationVisibilities><applicationVisibilities>
        <application>standard__LightningSalesConsole</application>
        <default>false</default>
        <visible>true</visible>
    </applicationVisibilities><applicationVisibilities>
        <application>standard__LightningService</application>
        <default>false</default>
        <visible>true</visible>
    </applicationVisibilities><applicationVisibilities>
        <application>standard__Marketing</application>
        <default>false</default>
        <visible>false</visible>
    </applicationVisibilities><applicationVisibilities>
        <application>standard__Platform</application>
        <default>false</default>
        <visible>false</visible>
    </applicationVisibilities><applicationVisibilities>
        <application>standard__Sales</application>
        <default>false</default>
        <visible>false</visible>
    </applicationVisibilities><applicationVisibilities>
        <application>standard__Service</application>
        <default>false</default>
        <visible>false</visible>
    </applicationVisibilities><applicationVisibilities>
        <application>standard__ServiceConsole</application>
        <default>false</default>
        <visible>false</visible>
    </applicationVisibilities><externalDataSourceAccesses>
        <enabled>false</enabled>
        <externalDataSource>asu_ps_lightning</externalDataSource>
    </externalDataSourceAccesses><fieldPermissions>
        <editable>true</editable>
        <field>AKB_Article_Feedback__c.Article_Author__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>AKB_Article_Feedback__c.Article_Id__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>AKB_Article_Feedback__c.Article_Number__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>AKB_Article_Feedback__c.Article_Title__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>AKB_Article_Feedback__c.Comments__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>AKB_Article_Feedback__c.Contact__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>AKB_Article_Feedback__c.Functional_Group__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>AKB_Article_Feedback__c.Helpful__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>AKB_Article_Feedback__c.Session_ID__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Academic_Group__c.Academic_Group_Code__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Academic_Group__c.Academic_Group_Status__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Academic_Group__c.Effective_Date__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Academic_Interest__c.Academic_Interest_Status__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Academic_Interest__c.GRE_Code__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Academic_Interest__c.Interest_Code__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Case_Assignment_Rule__c.Associate_Case_to_Active_Opportunity__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Case_Assignment_Rule__c.CTPColumn__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Case_Assignment_Rule__c.CTPGroup__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Case_Assignment_Rule__c.CTPVisible__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Case_Assignment_Rule__c.Campus__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Case_Assignment_Rule__c.Case_Record_Type_Id__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Case_Assignment_Rule__c.Category__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Case_Assignment_Rule__c.Chatter_Notification_Group__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Case_Assignment_Rule__c.Customer_Notice_Email_From_Name__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Case_Assignment_Rule__c.Email_Address__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Case_Assignment_Rule__c.Email_Template_ID__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Case_Assignment_Rule__c.Fallback_Queue_Id__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Case_Assignment_Rule__c.Functional_Group__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Case_Assignment_Rule__c.Label__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Case_Assignment_Rule__c.Origin__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Case_Assignment_Rule__c.Priority__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Case_Assignment_Rule__c.Queue_ID__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Case_Assignment_Rule__c.Queue_URL__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Case_Assignment_Rule__c.Receives_Chatter_Notifications__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Case_Assignment_Rule__c.Reply_To_Email_Address__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Case_Assignment_Rule__c.Sub_Category__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Case_Assignment_Rule__c.Type_of_Additional_Assignment_Needed__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Country__c.ISO_3_digit__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Country__c.ISO_Code__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>DataStage__c.extractId__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>DataStage__c.lastextracttime__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>DataStage__c.object__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Engagement_Contact__c.Case_Thread_Id__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Engagement_Contact__c.Success_Resource_Primary_Email__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Engagement_Contact__c.Success_Resource_Record__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>FERPA_Consent__c.FERPA_Comments__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Financial_Aid_Package__c.Aid_Year__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Financial_Aid_Package__c.EFC_Range__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Financial_Aid_Package__c.FAFSA_Date_Received__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Financial_Aid_Package__c.Fin_Aid_Package_Date__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Financial_Aid_Package__c.Financial_Aid_Status__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Financial_Aid_Package__c.Pell_Eligibility__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Financial_Aid_Package__c.Promise_Cohort__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Key_Value__c.Geomarket_Code__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Key_Value__c.Geomarket_ZIP__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Lead_Interest__c.Academic_Interest__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Lead_Interest__c.College__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Lead_Interest__c.Contact__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Lead_Interest__c.Eligibility__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Lead_Interest__c.External_Application_Number__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Lead_Interest__c.Leads__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Lead_Interest__c.Plan__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Lead_Interest__c.Primary_Source__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Lead_Interest__c.Qualifying__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Lead_Interest__c.Secondary_Source__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Lead_Interest__c.Send_Email_ID__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Lead_Interest__c.Status__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Lead_Interest__c.Term__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Lead_Interest__c.Test_Record__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Lead_Interest__c.Type__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Location__c.Location_Status__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>LostEmail__c.SPAM__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Organization__c.Effective_Date__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Organization__c.Organization_Descr__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Organization__c.Organization_Status__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Organization__c.Program__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>PKB_Article_Feedback_Deflection__c.Article_Author__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>PKB_Article_Feedback_Deflection__c.Functional_Group__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>PKB_Article_Feedback_Deflection__c.Type__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Plan__c.ASU_Online__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Plan__c.Available_in_Degree_Search__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Plan__c.Degree_Search_Name__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Plan__c.Degree__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Plan__c.Diploma_Description__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Plan__c.Organization__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Plan__c.Plan_Status__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Plan__c.Plan_Type__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Plan__c.Plan_URL__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Plan__c.Program__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Plan__c.Transcript_Description__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Plan__c.eAdvisor_Organization__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Previous_Education__c.ASU_Geomarket__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Previous_Education__c.ATP_Code__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Previous_Education__c.Account__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Previous_Education__c.Class_Rank_Percentile__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Previous_Education__c.Class_Rank__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Previous_Education__c.Class_Size__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Previous_Education__c.Degree_Type__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Previous_Education__c.Degree__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Previous_Education__c.GPA__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Previous_Education__c.Graduation_Date__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Previous_Education__c.Institution_Type__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Previous_Education__c.Is_Last_High_School_Attended__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Previous_Education__c.Source__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Program__c.Academic_Group__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Program__c.Campus__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Program__c.Career__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Program__c.Effective_Date__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Program__c.Program_Status__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Recruitment_Call__c.Call_Comments__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Recruitment_Call__c.Call_Origin__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Recruitment_Call__c.Call_Result__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Recruitment_Call__c.Call_Success__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Recruitment_Call__c.Call_Type__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Recruitment_Call__c.Campaign__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Recruitment_Call__c.Created_By_Role__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Relationship__c.Account__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Relationship__c.Active_Relationship__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Relationship__c.Contact__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Relationship__c.Reciprocal_Relationship__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Relationship__c.Related_Account__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Relationship__c.Related_Contact__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Relationship__c.Relationship_End_Date__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Relationship__c.Relationship_Notes__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Relationship__c.Relationship_Start_Date__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Relationship__c.Relationship_Type__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Relationship__c.Title__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Service_Indicator__c.SI_Code__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Service_Indicator__c.SI_Description__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Service_Indicator__c.SI_End_Date__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Service_Indicator__c.SI_End_Term__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Service_Indicator__c.SI_Positive_Service_Indicator__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Service_Indicator__c.SI_Reason__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Service_Indicator__c.SI_Start_Date__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Service_Indicator__c.SI_Start_Term__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Student_Account__c.Account_Balance__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Student_Account__c.Credit_Balance__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Student_Account__c.Direct_Deposit__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Student_Account__c.Future_Balance__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Student_Group__c.SG_Description__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Student_Group__c.SG_Effective_Date__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Student_Group__c.SG_PeopleSoft_Code__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Student_Group__c.SG_Status__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Student_Program_Plan__c.Action_Reason__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Student_Program_Plan__c.Action__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Student_Program_Plan__c.Admit_Term__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Student_Program_Plan__c.Application_Number__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Student_Program_Plan__c.Campus__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Student_Program_Plan__c.Career_Number__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Student_Program_Plan__c.Career__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Student_Program_Plan__c.College_Diploma_Description__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Student_Program_Plan__c.Completion_Term__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Student_Program_Plan__c.Contact__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Student_Program_Plan__c.Degree_Conferral_Date__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Student_Program_Plan__c.Degree__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Student_Program_Plan__c.Effective_Date__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Student_Program_Plan__c.Plan_Code__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Student_Program_Plan__c.Plan_Description__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Student_Program_Plan__c.Plan_Sequence__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Student_Program_Plan__c.Plan_Transcript_Description__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Student_Program_Plan__c.Plan_Type_Text__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Student_Program_Plan__c.Plan_URL__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Student_Program_Plan__c.Primary_Flag__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Student_Program_Plan__c.Program_Code__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Student_Program_Plan__c.Program_Description__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Student_Program_Plan__c.Status__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Student_Program_Subplan__c.Subplan_Description__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Student_Program_Subplan__c.Subplan_Transcript_Description__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Student_Program_Subplan__c.Subplan_Type__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Student_Program_Subplan__c.Subplan_code__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Success_Coach_Case_Flag_Rule__c.Flag_Key__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Success_Coach_Case_Flag_Rule__c.Flag_Value__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Success_Coach_Case_Flag__c.Category__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Success_Coach_Case_Flag__c.CreateCase__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Success_Coach_Case_Flag__c.FunctionalGroup__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Success_Coach_Case_Flag__c.IsActive__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Success_Coach_Case_Flag__c.Origin__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Success_Coach_Case_Flag__c.Priority__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Success_Coach_Case_Flag__c.SendEmail__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Success_Coach_Case_Flag__c.Status__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Success_Coach_Case_Flag__c.StoredProcedureName__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Success_Coach_Case_Flag__c.Type__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Success_Student__c.Coach_Contact_Preference__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Success_Student__c.Coach_Engagement__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Success_Student__c.Coach_Enrollment_Status__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Success_Student__c.Success_Pod__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Term__c.PeopleSoft_Code__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Term__c.Semester__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Term__c.Session_A_C_Close_Date__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Term__c.Session_A_C_Start_Date__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Term__c.Session_B_Close_Date__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Term__c.Session_B_Start_Date__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Term__c.Term_Status__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Territory_Assignment_Rule__c.Assignment_By_State__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Territory_Assignment_Rule__c.Assignment_by_Country__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Territory_Assignment_Rule__c.Campus__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Territory_Assignment_Rule__c.Defer_Territory_Assignment__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Territory_Assignment_Rule__c.Geomarket__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Territory_Assignment_Rule__c.International__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Territory_Assignment_Rule__c.Location__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Territory_Assignment_Rule__c.National_Scholarship__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Territory_Assignment_Rule__c.Opportunity_Type__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Territory_Assignment_Rule__c.Previous_User_ID__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Territory_Assignment_Rule__c.Range_End__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Territory_Assignment_Rule__c.Range_Start__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Territory_Assignment_Rule__c.Rule_Key__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Territory_Assignment_Rule__c.Rule_Type__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Territory_Assignment_Rule__c.User_Name__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Territory_Assignment_Rule__c.User__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>true</editable>
        <field>Test_Score__c.SAT_Pre_2016_Score__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Test_Score__c.Test_Component_Percentile__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Test_Score__c.Test_Component_Score__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Test_Score__c.Test_Component__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Test_Score__c.Test_Date__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Test_Score__c.Test_Record_Number__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Test_Score__c.Test_Source__c</field>
        <readable>true</readable>
    </fieldPermissions><fieldPermissions>
        <editable>false</editable>
        <field>Test_Score__c.Test_Type__c</field>
        <readable>true</readable>
    </fieldPermissions><layoutAssignments>
        <layout>AKB_Article_Feedback__c-AKB Article Feedback Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>ASU_STDNT_RETENTION_SNP__x-Student Retention Snapshot %28external%29 Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>ASU_STDNT_RETENTION__x-Student Retention %28external%29 Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Academic_Group__c-Academic Group Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Academic_Interest__c-Academic Interest Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Account-External Mastered Contact Layout</layout>
        <recordType>Account.External_Mastered_Contact</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Account-External Mastered Org Layout</layout>
        <recordType>Account.External_Mastered_Org</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Account-SF Mastered Contact Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Account-SF Mastered Contact Layout</layout>
        <recordType>Account.SF_Mastered_Contact</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Account-SF Mastered Org Layout</layout>
        <recordType>Account.SF_Mastered_Org</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Asset-Asset Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Bizcard_Campaign_Link__c-Bizcard Campaign Link Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Campaign-Cohort Layout</layout>
        <recordType>Campaign.Cohort</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Campaign-Communication Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Campaign-Communication Layout</layout>
        <recordType>Campaign.Marketing</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Campaign-Communication Layout</layout>
        <recordType>Campaign.Subscription_Center</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Campaign-Corporate Relations Layout</layout>
        <recordType>Campaign.Corporate_Relations</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Campaign-Course Layout</layout>
        <recordType>Campaign.Course</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Campaign-EOSS Event Layout</layout>
        <recordType>Campaign.EOSS_Event</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Campaign-Event Layout</layout>
        <recordType>Campaign.Event</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Campaign-Interest Layout</layout>
        <recordType>Campaign.Interest</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Campaign-Other Source Layout</layout>
        <recordType>Campaign.Other_Source</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Campaign-Scholarship Layout</layout>
        <recordType>Campaign.Scholarship</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>CampaignMember-Campaign Member Page Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>CampaignMember-Campaign Member Page Layout</layout>
        <recordType>CampaignMember.All_Students</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>CampaignMember-Campaign Member Page Layout</layout>
        <recordType>CampaignMember.Subscription_Center_Campaign_Member</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>CampaignMember-Corporate Relations Member Page Layout</layout>
        <recordType>CampaignMember.Corporate_Relations_Member</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Case-Case Feed - Advisor Outreach</layout>
        <recordType>Case.ASU_Advisor_Outreach</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Case-Case Feed - Coach Outreach</layout>
        <recordType>Case.ASU_Coach_Outreach</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Case-Case Feed - Student Outreach</layout>
        <recordType>Case.ASU_Student_Outreach</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Case-Case Feed Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Case-Case Feed Layout ADMIN</layout>
        <recordType>Case.ASU_Admission_Services</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Case-Case Feed Layout ADMIN</layout>
        <recordType>Case.ASU_Retention_Outreach</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Case-Case Feed Layout ADMIN</layout>
        <recordType>Case.ASU_Service</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>CaseClose-Close Case - ASU Advisor Outreach</layout>
        <recordType>Case.ASU_Advisor_Outreach</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>CaseClose-Close Case - ASU Coach Outreach</layout>
        <recordType>Case.ASU_Coach_Outreach</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>CaseClose-Close Case - Student Outreach</layout>
        <recordType>Case.ASU_Student_Outreach</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>CaseClose-Close Case Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>CaseClose-Close Case Layout</layout>
        <recordType>Case.ASU_Admission_Services</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>CaseClose-Close Case Layout</layout>
        <recordType>Case.ASU_Service</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>CaseClose-Retention Outreach Close Case Layout</layout>
        <recordType>Case.ASU_Retention_Outreach</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Case_Assignment_Rule__c-Case Assignment Rule Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Case_Creation_Indicator__c-Case Creation Indicator Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>CollaborationGroup-Group Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Contact-Feed - External Mastered Contact Layout for ADMIN</layout>
        <recordType>Contact.External_Mastered</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Contact-Feed - SF Mastered Contact Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Contact-Feed - SF Mastered Contact Layout</layout>
        <recordType>Contact.SF_Mastered</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Contract-Contract Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Country__c-Country Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>DataStage__c-DataStage Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Degree_Name__c-Degree Name Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>DuplicateRecordSet-Duplicate Record Set Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>EmailMessage-Email Message Layout - Email-to-Case</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Engagement_Contact__c-Engagement Contact Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Engagement_Message__c-Engagement Message Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Engagement_Planned_Message__c-Engagement Planned Message Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Engagement__c-Engagement Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Engagement__c-Engagement Layout</layout>
        <recordType>Engagement__c.ASU_Advisor_Outreach</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Engagement__c-Engagement Layout</layout>
        <recordType>Engagement__c.ASU_Coach_Outreach</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Engagement__c-Engagement Layout</layout>
        <recordType>Engagement__c.None</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Event-Event Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>FAQ__kav-FAQ Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>FERPA_Consent__c-FERPA Consent for Access Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>FeedItem-Feed Item Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Financial_Aid_Package__c-Financial Aid Package Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Financial_Aid_Status__x-Financial Aid Status Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>GPA_Scale__c-GPA Scale Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Global-Global Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>How_To__kav-How To Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Idea-Idea Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Idea-Idea Layout</layout>
        <recordType>Idea.InternalIdeasIdeaRecordType</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Idea-Idea Layout</layout>
        <recordType>Idea.Record_type_for_community_09ad00000019KjrAAE_entity_Idea</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Informational__kav-Informational Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>JBT_RET_ACAD_SUMMARY_VW__x-Academic Summary %28external%29 Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>JBT_RET_CLASS_XFER__x-Transfer Coursework %28external%29 Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>JBT_RET_FINAID_INDICATORS__x-Financial Aid Indicator %28external%29 Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>JBT_RET_FINAID_UNRESOLVED__x-Financial Aid Indicator %28external%29 Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>JBT_RET_GENERAL_LEFT__x-Student Demographic Data %28external%29 Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>JBT_RET_GENERAL_RIGHT__x-Student Program Data %28external%29 Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>JBT_RET_MYASU_ACCESS_CNT_VW__x-MyASU Usage Term %28external%29 Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>JBT_RET_OTH_IND1_VW__x-Retention Indicator %28external%29 Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>JBT_RET_PROFILE_HEADER_VW__x-Student Profile Page Header %28external%29 Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>JBT_RET_TERMS_VW__x-Relative Term Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Key_Value__c-Key Value Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Key_Value__c-Key Value Layout</layout>
        <recordType>Key_Value__c.Geomarket_Code_Map</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Lead-Lead Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Lead-Lead Layout</layout>
        <recordType>Lead.Processing</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Lead-Lead Layout</layout>
        <recordType>Lead.Prospective_Student</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Lead_Interest__c-Lead Interest Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Lead_Interest__c-Lead Interest Layout</layout>
        <recordType>Lead_Interest__c.User</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>LinkedArticle-Linked Article Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Location__c-Location Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>LostEmail__c-LostEmail Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Macro-Macro Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Marketing_Cloud_Business_Unit__c-Marketing Cloud Business Unit Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Match_Email_Exclusion__c-Match Email Exclusion Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Opportunity-Corporate_Relations</layout>
        <recordType>Opportunity.Corporate_Relations_Opportunity</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Opportunity-Feed - Graduate Application Layout</layout>
        <recordType>Opportunity.Graduate_Application</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Opportunity-Feed - Graduate Prospect Layout</layout>
        <recordType>Opportunity.Graduate_Prospect</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Opportunity-Feed - Opportunity Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Opportunity-Feed - Undergraduate Application Layout</layout>
        <recordType>Opportunity.Undergraduate_Application</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Opportunity-Feed - Undergraduate Prospect Layout</layout>
        <recordType>Opportunity.Undergraduate_Prospect</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>OpportunityLineItem-Opportunity Product Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Organization__c-Organization Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>PKB_Article_Feedback_Deflection__c-PKB Article Deflection Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>PKB_Featured__c-PKB Featured Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>PS_ASU_SP_ACAD_ADV__x-Academic Advisor %28external%29 Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>PS_ASU_SP_AC_STNDV__x-Academic Standing %28external%29 Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>PS_ASU_SP_ADNOTE_V__x-Advisor Note %28external%29 Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>PS_ASU_SP_ASR_CLSV__x-Class Academic Student Record %28external%29 Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>PS_ASU_SP_CLASS_V__x-Class %28external%29 Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>PS_ASU_SP_COMMNT_V__x-Comment %28external%29 Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>PS_ASU_SP_DEF_STSV__x-Defense Status %28external%29 Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>PS_ASU_SP_ENRHLD_V__x-Enrollment Hold Indicator %28external%29 Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>PS_ASU_SP_FA_BAL_V__x-Finance Account Balance %28external%29 Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>PS_ASU_SP_FA_SUM_V__x-Financial Aid Summary %28external%29 Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>PS_ASU_SP_GCEXAMV__x-Graduate Exam Status %28external%29 Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>PS_ASU_SP_GCPETV__x-Graduate Petition Status %28external%29 Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>PS_ASU_SP_GUEST_V__x-Guest Comment %28external%29 Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>PS_ASU_SP_HOLDCNTV__x-Academic Hold %28external%29 Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>PS_ASU_SP_REC_GRAD__x-Recent Graduation Term %28external%29 Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>PS_ASU_SP_SUBPLANV__x-Student Subplan %28external%29 Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>PS_ASU_SP_SVCIND_V__x-Service Indicator %28external%29 Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>PS_ASU_SP_TRNSFR_V__x-Transfer Class By Exam %28external%29 Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>PS_ASU_SR_ASR_INDV__x-Academic Status Report Info %28external%29 Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>PS_ASU_SR_COL_PLAN__x-Student Graduate Plan %28external%29 Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>PS_ASU_SR_INDASR_V__x-Academic Status Report Indicator %28ext%29 Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>PS_Country_Map__c-PS Country Map Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>PS_STDNT_CAR_MLSTN__x-Academic Milestone %28external%29 Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>PS_STDNT_TEST_COMP__x-Test Score %28external%29 Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Plan__c-Plan Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Portal_Email__c-Portal Email Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Portal_Email__c-Portal Email Layout</layout>
        <recordType>Portal_Email__c.Advisor</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Portal_Email__c-Portal Email Layout</layout>
        <recordType>Portal_Email__c.Coach</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Previous_Education__c-Previous Education Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Pricebook2-Price Book Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>PricebookEntry-Price Book Entry Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Product2-Product Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Program__c-Program Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>QuickText-Quick Text Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Recruitment_Call__c-Recruitment Call Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Recruitment_Call__c-Recruitment Call Layout</layout>
        <recordType>Recruitment_Call__c.Recruitment_Call</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Relationship__c-Account to Account Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Relationship__c-Account to Account Layout</layout>
        <recordType>Relationship__c.Account_to_Account</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Relationship__c-Account to Account Layout</layout>
        <recordType>Relationship__c.Account_to_Contact</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Relationship__c-Account to Account Reciprocal Layout</layout>
        <recordType>Relationship__c.Account_to_Account_Reciprocal</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Relationship__c-Contact to Account Layout</layout>
        <recordType>Relationship__c.Contact_to_Account</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Relationship__c-Contact to Contact Layout</layout>
        <recordType>Relationship__c.Contact_to_Contact</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Relationship__c-Contact to Contact Reciprocal Layout</layout>
        <recordType>Relationship__c.Contact_to_Contact_Reciprocal</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Rest_Service_Setting__mdt-Rest Service Setting Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>SearchPromotionRule-Promoted Search Term Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Service_Indicator__c-Service Indicator Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Solution-Solution Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Student_Account__c-Student Account Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Student_Accounts__x-Student Account Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Student_Group__c-Student Group Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Student_Profile_Term__c-Student Profile Term Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Student_Program_Plan__c-Student Program Plan Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Student_Program_Subplan__c-Student Sub Plan Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Success_Coach_Case_Flag_Rule__c-Success Coach Case Flag Rule Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Success_Coach_Case_Flag__c-Success Coach Case Flag Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Success_Pod__c-Success Pod Advisor Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Success_Pod__c-Success Pod Advisor Layout</layout>
        <recordType>Success_Pod__c.Advisor</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Success_Pod__c-Success Pod Coach Layout</layout>
        <recordType>Success_Pod__c.Coach</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Success_Resource_Plan__c-Success Resource Plan Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Success_Resource_Skill__c-Success Resource Skill Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Success_Resource__c-Success Resource Admin Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Success_Resource__c-Success Resource Admin Layout</layout>
        <recordType>Success_Resource__c.Advisor</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Success_Resource__c-Success Resource Admin Layout</layout>
        <recordType>Success_Resource__c.Coach</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Success_Skill__c-Success Skill Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Success_Student__c-Success Student Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Task-Task Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Task-Task Layout</layout>
        <recordType>Task.Admin_Task_Layout</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Task-Task Layout</layout>
        <recordType>Task.User_Task_Layout</recordType>
    </layoutAssignments><layoutAssignments>
        <layout>Term__c-Term Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Territory_Assignment_Rule__c-Auto Territory Assignment Rule Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Test_Engagement_Contacts__c-Test Engagement Contact Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>Test_Score__c-Test Score Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>User-User Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>UserAlt-User Profile Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>UserProvisioningRequest-User Provisioning Request Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>me3_Career__c-me3 Career Layout</layout>
    </layoutAssignments><layoutAssignments>
        <layout>me3__c-me3 Layout</layout>
    </layoutAssignments><objectPermissions>
        <allowCreate>true</allowCreate>
        <allowDelete>false</allowDelete>
        <allowEdit>true</allowEdit>
        <allowRead>true</allowRead>
        <modifyAllRecords>false</modifyAllRecords>
        <object>AKB_Article_Feedback__c</object>
        <viewAllRecords>false</viewAllRecords>
    </objectPermissions><objectPermissions>
        <allowCreate>false</allowCreate>
        <allowDelete>false</allowDelete>
        <allowEdit>false</allowEdit>
        <allowRead>true</allowRead>
        <modifyAllRecords>false</modifyAllRecords>
        <object>Academic_Group__c</object>
        <viewAllRecords>true</viewAllRecords>
    </objectPermissions><objectPermissions>
        <allowCreate>false</allowCreate>
        <allowDelete>false</allowDelete>
        <allowEdit>false</allowEdit>
        <allowRead>true</allowRead>
        <modifyAllRecords>false</modifyAllRecords>
        <object>Academic_Interest__c</object>
        <viewAllRecords>true</viewAllRecords>
    </objectPermissions><objectPermissions>
        <allowCreate>false</allowCreate>
        <allowDelete>false</allowDelete>
        <allowEdit>false</allowEdit>
        <allowRead>true</allowRead>
        <modifyAllRecords>false</modifyAllRecords>
        <object>Case_Assignment_Rule__c</object>
        <viewAllRecords>false</viewAllRecords>
    </objectPermissions><objectPermissions>
        <allowCreate>false</allowCreate>
        <allowDelete>false</allowDelete>
        <allowEdit>false</allowEdit>
        <allowRead>true</allowRead>
        <modifyAllRecords>false</modifyAllRecords>
        <object>Country__c</object>
        <viewAllRecords>true</viewAllRecords>
    </objectPermissions><objectPermissions>
        <allowCreate>false</allowCreate>
        <allowDelete>false</allowDelete>
        <allowEdit>false</allowEdit>
        <allowRead>true</allowRead>
        <modifyAllRecords>false</modifyAllRecords>
        <object>Degree_Name__c</object>
        <viewAllRecords>true</viewAllRecords>
    </objectPermissions><objectPermissions>
        <allowCreate>false</allowCreate>
        <allowDelete>false</allowDelete>
        <allowEdit>false</allowEdit>
        <allowRead>true</allowRead>
        <modifyAllRecords>false</modifyAllRecords>
        <object>Document</object>
        <viewAllRecords>false</viewAllRecords>
    </objectPermissions><objectPermissions>
        <allowCreate>false</allowCreate>
        <allowDelete>false</allowDelete>
        <allowEdit>false</allowEdit>
        <allowRead>true</allowRead>
        <modifyAllRecords>false</modifyAllRecords>
        <object>FERPA_Consent__c</object>
        <viewAllRecords>true</viewAllRecords>
    </objectPermissions><objectPermissions>
        <allowCreate>true</allowCreate>
        <allowDelete>false</allowDelete>
        <allowEdit>true</allowEdit>
        <allowRead>true</allowRead>
        <modifyAllRecords>false</modifyAllRecords>
        <object>Financial_Aid_Package__c</object>
        <viewAllRecords>true</viewAllRecords>
    </objectPermissions><objectPermissions>
        <allowCreate>false</allowCreate>
        <allowDelete>false</allowDelete>
        <allowEdit>false</allowEdit>
        <allowRead>true</allowRead>
        <modifyAllRecords>false</modifyAllRecords>
        <object>GPA_Scale__c</object>
        <viewAllRecords>true</viewAllRecords>
    </objectPermissions><objectPermissions>
        <allowCreate>false</allowCreate>
        <allowDelete>false</allowDelete>
        <allowEdit>false</allowEdit>
        <allowRead>true</allowRead>
        <modifyAllRecords>false</modifyAllRecords>
        <object>Key_Value__c</object>
        <viewAllRecords>true</viewAllRecords>
    </objectPermissions><objectPermissions>
        <allowCreate>false</allowCreate>
        <allowDelete>false</allowDelete>
        <allowEdit>false</allowEdit>
        <allowRead>true</allowRead>
        <modifyAllRecords>false</modifyAllRecords>
        <object>Lead_Interest__c</object>
        <viewAllRecords>true</viewAllRecords>
    </objectPermissions><objectPermissions>
        <allowCreate>false</allowCreate>
        <allowDelete>false</allowDelete>
        <allowEdit>false</allowEdit>
        <allowRead>true</allowRead>
        <modifyAllRecords>false</modifyAllRecords>
        <object>Location__c</object>
        <viewAllRecords>true</viewAllRecords>
    </objectPermissions><objectPermissions>
        <allowCreate>false</allowCreate>
        <allowDelete>false</allowDelete>
        <allowEdit>false</allowEdit>
        <allowRead>true</allowRead>
        <modifyAllRecords>false</modifyAllRecords>
        <object>Organization__c</object>
        <viewAllRecords>true</viewAllRecords>
    </objectPermissions><objectPermissions>
        <allowCreate>false</allowCreate>
        <allowDelete>false</allowDelete>
        <allowEdit>false</allowEdit>
        <allowRead>true</allowRead>
        <modifyAllRecords>false</modifyAllRecords>
        <object>Plan__c</object>
        <viewAllRecords>true</viewAllRecords>
    </objectPermissions><objectPermissions>
        <allowCreate>true</allowCreate>
        <allowDelete>false</allowDelete>
        <allowEdit>true</allowEdit>
        <allowRead>true</allowRead>
        <modifyAllRecords>false</modifyAllRecords>
        <object>Previous_Education__c</object>
        <viewAllRecords>true</viewAllRecords>
    </objectPermissions><objectPermissions>
        <allowCreate>false</allowCreate>
        <allowDelete>false</allowDelete>
        <allowEdit>false</allowEdit>
        <allowRead>true</allowRead>
        <modifyAllRecords>false</modifyAllRecords>
        <object>Program__c</object>
        <viewAllRecords>true</viewAllRecords>
    </objectPermissions><objectPermissions>
        <allowCreate>true</allowCreate>
        <allowDelete>false</allowDelete>
        <allowEdit>true</allowEdit>
        <allowRead>true</allowRead>
        <modifyAllRecords>false</modifyAllRecords>
        <object>Recruitment_Call__c</object>
        <viewAllRecords>true</viewAllRecords>
    </objectPermissions><objectPermissions>
        <allowCreate>true</allowCreate>
        <allowDelete>false</allowDelete>
        <allowEdit>true</allowEdit>
        <allowRead>true</allowRead>
        <modifyAllRecords>false</modifyAllRecords>
        <object>Relationship__c</object>
        <viewAllRecords>false</viewAllRecords>
    </objectPermissions><objectPermissions>
        <allowCreate>true</allowCreate>
        <allowDelete>false</allowDelete>
        <allowEdit>true</allowEdit>
        <allowRead>true</allowRead>
        <modifyAllRecords>false</modifyAllRecords>
        <object>Service_Indicator__c</object>
        <viewAllRecords>true</viewAllRecords>
    </objectPermissions><objectPermissions>
        <allowCreate>true</allowCreate>
        <allowDelete>false</allowDelete>
        <allowEdit>true</allowEdit>
        <allowRead>true</allowRead>
        <modifyAllRecords>false</modifyAllRecords>
        <object>Student_Account__c</object>
        <viewAllRecords>false</viewAllRecords>
    </objectPermissions><objectPermissions>
        <allowCreate>true</allowCreate>
        <allowDelete>false</allowDelete>
        <allowEdit>false</allowEdit>
        <allowRead>true</allowRead>
        <modifyAllRecords>false</modifyAllRecords>
        <object>Student_Group__c</object>
        <viewAllRecords>true</viewAllRecords>
    </objectPermissions><objectPermissions>
        <allowCreate>true</allowCreate>
        <allowDelete>false</allowDelete>
        <allowEdit>true</allowEdit>
        <allowRead>true</allowRead>
        <modifyAllRecords>false</modifyAllRecords>
        <object>Student_Program_Plan__c</object>
        <viewAllRecords>true</viewAllRecords>
    </objectPermissions><objectPermissions>
        <allowCreate>true</allowCreate>
        <allowDelete>false</allowDelete>
        <allowEdit>true</allowEdit>
        <allowRead>true</allowRead>
        <modifyAllRecords>false</modifyAllRecords>
        <object>Student_Program_Subplan__c</object>
        <viewAllRecords>false</viewAllRecords>
    </objectPermissions><objectPermissions>
        <allowCreate>true</allowCreate>
        <allowDelete>true</allowDelete>
        <allowEdit>true</allowEdit>
        <allowRead>true</allowRead>
        <modifyAllRecords>true</modifyAllRecords>
        <object>Success_Coach_Case_Flag_Rule__c</object>
        <viewAllRecords>true</viewAllRecords>
    </objectPermissions><objectPermissions>
        <allowCreate>true</allowCreate>
        <allowDelete>true</allowDelete>
        <allowEdit>true</allowEdit>
        <allowRead>true</allowRead>
        <modifyAllRecords>true</modifyAllRecords>
        <object>Success_Coach_Case_Flag__c</object>
        <viewAllRecords>true</viewAllRecords>
    </objectPermissions><objectPermissions>
        <allowCreate>false</allowCreate>
        <allowDelete>false</allowDelete>
        <allowEdit>false</allowEdit>
        <allowRead>true</allowRead>
        <modifyAllRecords>false</modifyAllRecords>
        <object>Term__c</object>
        <viewAllRecords>true</viewAllRecords>
    </objectPermissions><objectPermissions>
        <allowCreate>true</allowCreate>
        <allowDelete>false</allowDelete>
        <allowEdit>true</allowEdit>
        <allowRead>true</allowRead>
        <modifyAllRecords>false</modifyAllRecords>
        <object>Territory_Assignment_Rule__c</object>
        <viewAllRecords>false</viewAllRecords>
    </objectPermissions><objectPermissions>
        <allowCreate>true</allowCreate>
        <allowDelete>false</allowDelete>
        <allowEdit>true</allowEdit>
        <allowRead>true</allowRead>
        <modifyAllRecords>false</modifyAllRecords>
        <object>Test_Score__c</object>
        <viewAllRecords>true</viewAllRecords>
    </objectPermissions><recordTypeVisibilities>
        <default>false</default>
        <recordType>Account.External_Mastered_Contact</recordType>
        <visible>true</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>Account.External_Mastered_Org</recordType>
        <visible>true</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>Account.SF_Mastered_Contact</recordType>
        <visible>true</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>true</default>
        <personAccountDefault>true</personAccountDefault>
        <recordType>Account.SF_Mastered_Org</recordType>
        <visible>true</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>Campaign.Cohort</recordType>
        <visible>true</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>Campaign.Corporate_Relations</recordType>
        <visible>true</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>Campaign.Course</recordType>
        <visible>true</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>Campaign.EOSS_Event</recordType>
        <visible>true</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>true</default>
        <recordType>Campaign.Event</recordType>
        <visible>true</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>Campaign.Interest</recordType>
        <visible>true</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>Campaign.Marketing</recordType>
        <visible>true</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>Campaign.Other_Source</recordType>
        <visible>true</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>Campaign.Scholarship</recordType>
        <visible>true</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>Campaign.Subscription_Center</recordType>
        <visible>false</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>true</default>
        <recordType>CampaignMember.All_Students</recordType>
        <visible>true</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>CampaignMember.Corporate_Relations_Member</recordType>
        <visible>true</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>CampaignMember.Subscription_Center_Campaign_Member</recordType>
        <visible>false</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>Case.ASU_Admission_Services</recordType>
        <visible>true</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>Case.ASU_Advisor_Outreach</recordType>
        <visible>false</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>Case.ASU_Coach_Outreach</recordType>
        <visible>false</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>Case.ASU_Retention_Outreach</recordType>
        <visible>false</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>true</default>
        <personAccountDefault>true</personAccountDefault>
        <recordType>Case.ASU_Service</recordType>
        <visible>true</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>Case.ASU_Student_Outreach</recordType>
        <visible>false</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>Contact.External_Mastered</recordType>
        <visible>true</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>true</default>
        <personAccountDefault>true</personAccountDefault>
        <recordType>Contact.SF_Mastered</recordType>
        <visible>true</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>true</default>
        <recordType>Engagement__c.ASU_Advisor_Outreach</recordType>
        <visible>true</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>Engagement__c.ASU_Coach_Outreach</recordType>
        <visible>true</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>Engagement__c.None</recordType>
        <visible>true</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>Idea.InternalIdeasIdeaRecordType</recordType>
        <visible>false</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>Idea.Record_type_for_community_09ad00000019KjrAAE_entity_Idea</recordType>
        <visible>false</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>true</default>
        <personAccountDefault>true</personAccountDefault>
        <recordType>Key_Value__c.Geomarket_Code_Map</recordType>
        <visible>true</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>Lead.Processing</recordType>
        <visible>false</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>true</default>
        <personAccountDefault>true</personAccountDefault>
        <recordType>Lead.Prospective_Student</recordType>
        <visible>true</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>true</default>
        <personAccountDefault>true</personAccountDefault>
        <recordType>Lead_Interest__c.User</recordType>
        <visible>true</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>Opportunity.Corporate_Relations_Opportunity</recordType>
        <visible>false</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>Opportunity.Graduate_Application</recordType>
        <visible>true</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>true</default>
        <personAccountDefault>true</personAccountDefault>
        <recordType>Opportunity.Graduate_Prospect</recordType>
        <visible>true</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>Opportunity.Undergraduate_Application</recordType>
        <visible>true</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>Opportunity.Undergraduate_Prospect</recordType>
        <visible>true</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>Portal_Email__c.Advisor</recordType>
        <visible>false</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>Portal_Email__c.Coach</recordType>
        <visible>false</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>Recruitment_Call__c.Recruitment_Call</recordType>
        <visible>false</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>Relationship__c.Account_to_Account</recordType>
        <visible>true</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>Relationship__c.Account_to_Account_Reciprocal</recordType>
        <visible>false</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>Relationship__c.Account_to_Contact</recordType>
        <visible>false</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>true</default>
        <personAccountDefault>true</personAccountDefault>
        <recordType>Relationship__c.Contact_to_Account</recordType>
        <visible>true</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>Relationship__c.Contact_to_Contact</recordType>
        <visible>true</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>Relationship__c.Contact_to_Contact_Reciprocal</recordType>
        <visible>false</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>Success_Pod__c.Advisor</recordType>
        <visible>false</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>Success_Pod__c.Coach</recordType>
        <visible>false</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>Success_Resource__c.Advisor</recordType>
        <visible>false</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>Success_Resource__c.Coach</recordType>
        <visible>false</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>false</default>
        <recordType>Task.Admin_Task_Layout</recordType>
        <visible>false</visible>
    </recordTypeVisibilities><recordTypeVisibilities>
        <default>true</default>
        <recordType>Task.User_Task_Layout</recordType>
        <visible>true</visible>
    </recordTypeVisibilities><tabVisibilities>
        <tab>AKB_Article_Feedback__c</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Academic_Group__c</tab>
        <visibility>DefaultOff</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Academic_Interest__c</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Advisor_Portal</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Case_Assignment_Rule__c</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Case_Creation_Indicator__c</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Coach_Portal</tab>
        <visibility>DefaultOff</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Degree_Name__c</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Engagement_Contact__c</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Engagement_Message__c</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Engagement_Planned_Message__c</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Engagement__c</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>External_Object_Query</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Financial_Aid_Package__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Getting_Started_reg</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Getting_Started_social</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Key_Value__c</tab>
        <visibility>DefaultOff</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Lead_Interest__c</tab>
        <visibility>DefaultOff</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Location__c</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>LostEmail__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Marketing_Cloud_Business_Unit__c</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Match_Email_Exclusion__c</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>New_Corporate_Relations_Contact</tab>
        <visibility>DefaultOff</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>New_Prospect</tab>
        <visibility>DefaultOff</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>New_Prospective_Student</tab>
        <visibility>DefaultOff</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>New_Undergrad_Prospect</tab>
        <visibility>DefaultOff</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Organization__c</tab>
        <visibility>DefaultOff</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>PKB_2_Settings</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>PKB_Article_Feedback_Deflection__c</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>PKB_Featured__c</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>PS_Country_Map__c</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Plan__c</tab>
        <visibility>DefaultOff</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Portal_Email__c</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Previous_Education__c</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Profile_Explorer</tab>
        <visibility>DefaultOff</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Program__c</tab>
        <visibility>DefaultOff</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Recruitment_Call__c</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Search_Users</tab>
        <visibility>DefaultOff</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Service_Center</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Success_Coach_Case_Flag_Rule__c</tab>
        <visibility>DefaultOff</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Success_Coach_Case_Flag__c</tab>
        <visibility>DefaultOff</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Success_Pod__c</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Success_Portal</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Success_Resource_Plan__c</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Success_Resource_Skill__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Success_Resource__c</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Success_Skill__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Success_Student__c</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Term__c</tab>
        <visibility>DefaultOff</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Territory_Assignment_Rule__c</tab>
        <visibility>DefaultOff</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Test_Engagement_Contacts__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>Test_Score__c</tab>
        <visibility>DefaultOff</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>standard-Account</tab>
        <visibility>DefaultOff</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>standard-Asset</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>standard-Campaign</tab>
        <visibility>DefaultOff</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>standard-Case</tab>
        <visibility>DefaultOff</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>standard-CollaborationGroup</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>standard-Contact</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>standard-Contract</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>standard-Dashboard</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>standard-Document</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>standard-DuplicateRecordSet</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>standard-Idea</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>standard-Lead</tab>
        <visibility>DefaultOff</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>standard-Macro</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>standard-Opportunity</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>standard-Pricebook2</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>standard-Product2</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>standard-Solution</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>standard-StreamingChannel</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>standard-UserProfile</tab>
        <visibility>DefaultOff</visibility>
    </tabVisibilities><tabVisibilities>
        <tab>standard-UserProvisioningRequest</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities><userPermissions>
        <enabled>true</enabled>
        <name>AllowUniversalSearch</name>
    </userPermissions><userPermissions>
        <enabled>true</enabled>
        <name>AllowViewKnowledge</name>
    </userPermissions><userPermissions>
        <enabled>true</enabled>
        <name>ApiEnabled</name>
    </userPermissions><userPermissions>
        <enabled>true</enabled>
        <name>ChatterEditOwnPost</name>
    </userPermissions><userPermissions>
        <enabled>true</enabled>
        <name>ChatterInternalUser</name>
    </userPermissions><userPermissions>
        <enabled>true</enabled>
        <name>CreateCustomizeFilters</name>
    </userPermissions><userPermissions>
        <enabled>true</enabled>
        <name>CreateCustomizeReports</name>
    </userPermissions><userPermissions>
        <enabled>true</enabled>
        <name>EditEvent</name>
    </userPermissions><userPermissions>
        <enabled>true</enabled>
        <name>EditTask</name>
    </userPermissions><userPermissions>
        <enabled>true</enabled>
        <name>EmailSingle</name>
    </userPermissions><userPermissions>
        <enabled>true</enabled>
        <name>MassInlineEdit</name>
    </userPermissions><userPermissions>
        <enabled>true</enabled>
        <name>RunReports</name>
    </userPermissions><userPermissions>
        <enabled>true</enabled>
        <name>SelectFilesFromSalesforce</name>
    </userPermissions><userPermissions>
        <enabled>true</enabled>
        <name>ShowCompanyNameAsUserBadge</name>
    </userPermissions><userPermissions>
        <enabled>true</enabled>
        <name>SubscribeToLightningReports</name>
    </userPermissions><userPermissions>
        <enabled>true</enabled>
        <name>TransferAnyCase</name>
    </userPermissions><userPermissions>
        <enabled>true</enabled>
        <name>ViewHelpLink</name>
    </userPermissions><userPermissions>
        <enabled>true</enabled>
        <name>ViewSetup</name>
    </userPermissions></Profile>