<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <consoleConfig>
        <componentList>
            <alignment>right</alignment>
            <components>Console.BuiltInComponent.mostRecentlyUsed</components>
        </componentList>
        <detailPageRefreshMethod>none</detailPageRefreshMethod>
        <footerColor>#cccccc</footerColor>
        <headerColor>#990033</headerColor>
        <keyboardShortcuts>
            <defaultShortcuts>
                <action>FOCUS_CONSOLE</action>
                <active>true</active>
                <keyCommand>ESC</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>FOCUS_NAVIGATOR_TAB</action>
                <active>true</active>
                <keyCommand>V</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>FOCUS_DETAIL_VIEW</action>
                <active>true</active>
                <keyCommand>SHIFT+S</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>FOCUS_PRIMARY_TAB_PANEL</action>
                <active>true</active>
                <keyCommand>P</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>FOCUS_SUBTAB_PANEL</action>
                <active>true</active>
                <keyCommand>S</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>FOCUS_LIST_VIEW</action>
                <active>true</active>
                <keyCommand>N</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>FOCUS_FIRST_LIST_VIEW</action>
                <active>true</active>
                <keyCommand>SHIFT+F</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>FOCUS_SEARCH_INPUT</action>
                <active>true</active>
                <keyCommand>R</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>MOVE_LEFT</action>
                <active>true</active>
                <keyCommand>LEFT ARROW</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>MOVE_RIGHT</action>
                <active>true</active>
                <keyCommand>RIGHT ARROW</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>UP_ARROW</action>
                <active>true</active>
                <keyCommand>UP ARROW</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>DOWN_ARROW</action>
                <active>true</active>
                <keyCommand>DOWN ARROW</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>OPEN_TAB_SCROLLER_MENU</action>
                <active>true</active>
                <keyCommand>D</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>OPEN_TAB</action>
                <active>true</active>
                <keyCommand>T</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>CLOSE_TAB</action>
                <active>true</active>
                <keyCommand>C</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>REFRESH_TAB</action>
                <active>false</active>
                <keyCommand>SHIFT+R</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>ENTER</action>
                <active>true</active>
                <keyCommand>ENTER</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>EDIT</action>
                <active>true</active>
                <keyCommand>E</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>SAVE</action>
                <active>true</active>
                <keyCommand>CTRL+S</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>CONSOLE_LINK_DIALOG</action>
                <active>false</active>
                <keyCommand>U</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>HOTKEYS_PANEL</action>
                <active>false</active>
                <keyCommand>SHIFT+K</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>FOCUS_MACRO</action>
                <active>false</active>
                <keyCommand>M</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>FOCUS_FOOTER_PANEL</action>
                <active>false</active>
                <keyCommand>F</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>TOGGLE_LIST_VIEW</action>
                <active>false</active>
                <keyCommand>SHIFT+N</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>TOGGLE_LEFT_SIDEBAR</action>
                <active>false</active>
                <keyCommand>SHIFT+LEFT ARROW</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>TOGGLE_RIGHT_SIDEBAR</action>
                <active>false</active>
                <keyCommand>SHIFT+RIGHT ARROW</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>TOGGLE_TOP_SIDEBAR</action>
                <active>false</active>
                <keyCommand>SHIFT+UP ARROW</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>TOGGLE_BOTTOM_SIDEBAR</action>
                <active>false</active>
                <keyCommand>SHIFT+DOWN ARROW</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>TOGGLE_APP_LEVEL_COMPONENTS</action>
                <active>false</active>
                <keyCommand>Z</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>REOPEN_LAST_TAB</action>
                <active>false</active>
                <keyCommand>SHIFT+C</keyCommand>
            </defaultShortcuts>
        </keyboardShortcuts>
        <listPlacement>
            <location>left</location>
            <units>percent</units>
            <width>33</width>
        </listPlacement>
        <listRefreshMethod>none</listRefreshMethod>
        <liveAgentConfig>
            <enableLiveChat>true</enableLiveChat>
            <openNewAccountSubtab>false</openNewAccountSubtab>
            <openNewCaseSubtab>false</openNewCaseSubtab>
            <openNewContactSubtab>false</openNewContactSubtab>
            <openNewLeadSubtab>false</openNewLeadSubtab>
            <openNewVFPageSubtab>false</openNewVFPageSubtab>
            <showKnowledgeArticles>false</showKnowledgeArticles>
        </liveAgentConfig>
        <whitelistedDomains>pitch.asuonline.asu.edu</whitelistedDomains>
    </consoleConfig>
    <defaultLandingTab>standard-home</defaultLandingTab>
    <description>Service Console</description>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <isServiceCloudConsole>true</isServiceCloudConsole>
    <label>ASU Service</label>
    <logo>Administrator/ASU_White_Logo_with_background.png</logo>
    <preferences>
        <enableCustomizeMyTabs>true</enableCustomizeMyTabs>
        <enableKeyboardShortcuts>true</enableKeyboardShortcuts>
        <enableListViewHover>true</enableListViewHover>
        <enableListViewReskin>true</enableListViewReskin>
        <enableMultiMonitorComponents>true</enableMultiMonitorComponents>
        <enablePinTabs>true</enablePinTabs>
        <enableTabHover>true</enableTabHover>
        <enableTabLimits>false</enableTabLimits>
        <saveUserSessions>true</saveUserSessions>
    </preferences>
    <tabs>standard-Case</tabs>
    <tabs>standard-Contact</tabs>
    <tabs>standard-Knowledge</tabs>
    <tabs>standard-KnowledgePublishing</tabs>
    <tabs>standard-report</tabs>
    <tabs>standard-Dashboard</tabs>
    <tabs>standard-home</tabs>
    <tabs>standard-Chatter</tabs>
    <tabs>standard-QuickText</tabs>
    <tabs>standard-Opportunity</tabs>
    <tabs>standard-Macro</tabs>
    <tabs>New_Prospective_Student</tabs>
    <tabs>et4ae5__Business_Unit__c</tabs>
    <tabs>LiveAgent_Custom_Message__c</tabs>
    <tabs>standard-LiveChatTranscript</tabs>
    <tabs>standard-LiveAgentSupervisor</tabs>
    <tabs>standard-LiveChatVisitor</tabs>
    <tabs>standard-LiveAgentSession</tabs>
    <workspaceConfig>
        <mappings>
            <tab>LiveAgent_Custom_Message__c</tab>
        </mappings>
        <mappings>
            <tab>New_Prospective_Student</tab>
        </mappings>
        <mappings>
            <tab>et4ae5__Business_Unit__c</tab>
        </mappings>
        <mappings>
            <fieldName>ContactId</fieldName>
            <tab>standard-Case</tab>
        </mappings>
        <mappings>
            <tab>standard-Chatter</tab>
        </mappings>
        <mappings>
            <tab>standard-Contact</tab>
        </mappings>
        <mappings>
            <tab>standard-Dashboard</tab>
        </mappings>
        <mappings>
            <tab>standard-Knowledge</tab>
        </mappings>
        <mappings>
            <tab>standard-KnowledgePublishing</tab>
        </mappings>
        <mappings>
            <tab>standard-LiveAgentSession</tab>
        </mappings>
        <mappings>
            <tab>standard-LiveAgentSupervisor</tab>
        </mappings>
        <mappings>
            <tab>standard-LiveChatTranscript</tab>
        </mappings>
        <mappings>
            <tab>standard-LiveChatVisitor</tab>
        </mappings>
        <mappings>
            <tab>standard-Macro</tab>
        </mappings>
        <mappings>
            <fieldName>Contact__c</fieldName>
            <tab>standard-Opportunity</tab>
        </mappings>
        <mappings>
            <tab>standard-QuickText</tab>
        </mappings>
        <mappings>
            <tab>standard-home</tab>
        </mappings>
        <mappings>
            <tab>standard-report</tab>
        </mappings>
    </workspaceConfig>
</CustomApplication>
