AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
    AliusSlack:
        Type: 'AWS::Serverless::Function'
        Properties:
            Handler: alius_slack.lambda_handler
            Runtime: python3.8
            CodeUri: .
            Description: ''
            MemorySize: 256
            Timeout: 180
            Role: 'arn:aws:iam::187616753226:role/service-role/AliusSlack-role-262hnr8w'
            Events:
                Schedule1:
                    Type: Schedule
                    Properties:
                        Schedule: cron(0/5 15-0 ? * MON-FRI *)
            Layers:
                - 'arn:aws:lambda:us-east-1:187616753226:layer:PyGithub:1'
