reviewers:
    groups:
        repository-maintainers:
            - jdsanch8
            - mgilardi
    per_author:
        carlhussey-asu:
            - repository-maintainers
        jahami10:
            - repository-maintainers
        rnordmanASU:
            - repository-maintainers
        ShahanaASU:
            - repository-maintainers
options:
    ignore_draft: true
    ignored_keywords:
        - DO NOT REVIEW
    enable_group_assignment: false
