reviewers:
    groups:
        repository-maintainers:
            - jdsanch8
            - mgilardi
            - rnordmanASU
    per_author:
        ShahanaASU:
            - repository-maintainers
options:
    ignore_draft: true
    ignored_keywords:
        - DO NOT REVIEW
    enable_group_assignment: false
