name: Alius CI

on:
    workflow_dispatch:
    # push:
    #     branches:
    #         - main

jobs:
    run-alius-ci:
        runs-on: ubuntu-latest
        steps:
            - name: Run Alius CI
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - run: |
                  chmod +x "${GITHUB_WORKSPACE}/.github/workflows/AliusCI/alius_ci.sh"
                  "${GITHUB_WORKSPACE}/.github/workflows/AliusCI/alius_ci.sh"
