name: Alius CI Trigger

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    http-request-action:
        runs-on: ubuntu-latest
        steps:
            - name: Initiate HTTP request
              uses: fjogeleit/http-request-action@master
              with:
                  url: 'https://br1op9genk.execute-api.us-east-1.amazonaws.com/default/AliusCI'
                  customHeaders: '{"Authorization":"82C645A5E20FA9E3EECADEDF77668063FD12C831831","Repository":"${{ github.repository }}"}'
                  timeout: 90000
                  preventFailureOnNoResponse: 'true'
                  ignoreStatusCodes: '401,404,500,503'
