name: Branch Status

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    run-branch-status-report:
        runs-on: ubuntu-latest
        steps:
            - name: Run Branch Status Report
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - run: |
                  chmod +x "${GITHUB_WORKSPACE}/.github/workflows/BranchStatus/branch_status_report.sh"
                  "${GITHUB_WORKSPACE}/.github/workflows/BranchStatus/branch_status_report.sh"
    compile-branch-tracking-report:
        needs: run-branch-status-report
        runs-on: ubuntu-latest
        steps:
            - name: Setup tracking information
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - run: |
                  chmod +x branch_tracking_setup.sh
                  ./branch_tracking_setup.sh
              working-directory: ./.github/workflows/BranchStatus
            - name: Checkout repository wiki
              uses: actions/checkout@v3
              with:
                  repository: '${{ github.repository }}.wiki'
                  path: 'wiki'
            - name: Update tracking report
              run: |
                  chmod +x branch_tracking_report.sh
                  ./branch_tracking_report.sh
              working-directory: ./.github/workflows/BranchStatus
