name: Production Metadata Sync

on:
    workflow_dispatch:
    push:
        branches:
            - sync

jobs:
    production-metadata-sync:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: main
                  fetch-depth: 0
            - name: Run Git operations
              run: |
                  git config user.name "GitHub Actions"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git fetch origin
                  git pull --no-edit origin sync
            - name: Create pull request
              uses: peter-evans/create-pull-request@v5
              with:
                  commit-message: 'Metadata sync from SF PROD to GitHub'
                  title: 'GITHUB-ACTIONS[BOT]: PRODUCTION METADATA SYNC'
                  body: "Comparison is the fastest way to feel unhappy. Luckily, I'm not human, so I'm immune to your biological ailments."
                  reviewers: mgilardi, jdsanch8
                  branch: sync-pr
                  delete-branch: true
