name: Pull Request Auto Review

on:
    pull_request_target:
        types: [opened, ready_for_review, reopened]
        branches:
            - 'dev'
            - 'qa'
            - 'uat'
            - 'migration-**'
            - '**Migration**'
            - 'main'

jobs:
    pull-request-auto-review:
        name: Pull Request Auto Review
        runs-on: ubuntu-latest
        steps:
            - name: Request review based on set criteria
              uses: necojackarc/auto-request-review@v0.10.0
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  config: .github/workflows/PullRequestAutoReview/reviewers.yml
